@startuml
/'
  Заявки техникам
'/
title 
  **Заявки техникам 1**
end title

:|= \nИнициатор | \nработник обладающий \nправом запуска\n|
|= \nСтарт | \nпроцесс из живой ленты \n|;

:=**Задание**
====

|= \nЗадание |\n Зафиксировать заявку\n |
|= \nКто выполняет |\n Инициатор - сотрудник отдела \n"Собственная сеть кафе" \nи его подчиненных подразделений\n|
|= \nТекст задания |\n \n|
|= \nИнформация к выводу|\n \n|
|= \nПоля для заполнения | \n** * Название заявки**\n * Описание заявки\n** * Срочность**\n * Отвественный\n * Файлы инициатора \n|
|= \n Действие\n||
|= \nБитрикс|\nСохраняет в документе \nвсе введенные значения\n|
<

:=Автоматически
====

* Заполняет поле 
 //{Инициатор процесса} = Кто стартовал//
* Заполняет поле СтатусЗаявки = "новая"
* Заполняет поле 
 //{Время создания заявки} = SysNow//
]

if ({Срочность}) is (Обычная) then
:= Автоматически
====

//{Крайний Срок} = {Время Создания Заявки} + 5 рабочих дней//
]
else (Срочная)

  := Автоматически
  ====
  
  //{Крайний Срок} = {Время Создания Заявки} + 1 рабочий день//
  ]
endif

:=**Задание**
====

|= \nЗадание |\n //{Название задания}//\n Ознакомится с заявкой\n |
|= \nКто выполняет |\n Ответственный \n|
|= \nТекст задания |\n Необходимо нажать кнопку "Ознакомится"\n|
|= \nИнформация к выводу|\n * {Инициатор процесса}\n * {Крайний срок}\n * {Описание заявки}\n * {Статус заявки}\n|
|= \nПоля для заполнения | |
|= \nДействие\n |\n Ознакомиться \n|
|= \nБитрикс||
<

floating note left
    **Отвественному**
    ====
    Вам назначена новая 
    заявка срок исполнения 
    до {КвайнийСрок} включительно. 
    Перейдите в свои задания 
    и ознакомьтесь с заявкой
end note

:= Автоматически
====
 * {Дата ознакомления} = SysNow
 * {Время Реакции На Ознакомление} = {Дата ознакомления} - {Дата Создания Заявки} c
 * Статус = "ознакомлен"

]


@enduml
